/**
 * Major Arcana card data for static HTML page generation.
 *
 * Source of truth for card interpretation pages served on GitHub Pages.
 * Data mirrors backend/src/tarotData.ts MAJOR_ARCANA, enriched with
 * slugs, element/planet associations, and love/career/money themes
 * for SEO-rich content pages.
 */

export const MAJOR_ARCANA = [
  {
    id: 0, slug: 'fool', name: '바보', nameEn: 'The Fool', symbol: '🃏',
    element: '공기', planet: '천왕성',
    keywordsUp: ['새시작', '자유', '모험', '순수', '무한한가능성'],
    keywordsDown: ['무모함', '경솔', '미숙', '판단부족'],
    meaningUp: '새로운 시작과 무한한 가능성이 열려있어요. 두려움 없이 한 걸음 내디뎌보세요.',
    meaningDown: '너무 서두르고 있을 수 있어요. 한 박자 쉬어가며 신중하게 결정하세요.',
    loveAdvice: '새로운 인연이나 관계의 새로운 단계를 의미해요. 솔직하고 순수한 마음으로 다가가보세요.',
    careerAdvice: '새로운 프로젝트나 이직의 기회가 있어요. 도전을 두려워하지 마세요.',
    moneyAdvice: '새로운 투자나 수입 경로가 열릴 수 있어요. 다만 너무 무모한 결정은 피하세요.',
  },
  {
    id: 1, slug: 'magician', name: '마법사', nameEn: 'The Magician', symbol: '🧙',
    element: '공기', planet: '수성',
    keywordsUp: ['창조', '기술', '의지력', '집중', '성공'],
    keywordsDown: ['조작', '기만', '재능낭비', '자신감부족'],
    meaningUp: '당신에게 필요한 모든 것이 이미 갖춰져 있어요. 능력을 믿고 행동하세요.',
    meaningDown: '재능을 제대로 활용하지 못하고 있어요. 자신감을 되찾을 시간이에요.',
    loveAdvice: '당신의 매력과 능력이 빛나는 시기예요. 주도적으로 다가가보세요.',
    careerAdvice: '필요한 기술과 자원이 모두 있어요. 자신감을 가지고 추진하면 성공할 수 있어요.',
    moneyAdvice: '돈을 만들어낼 수 있는 능력이 있어요. 아이디어를 실행에 옮겨보세요.',
  },
  {
    id: 2, slug: 'high-priestess', name: '여사제', nameEn: 'The High Priestess', symbol: '🌙',
    element: '물', planet: '달',
    keywordsUp: ['직관', '지혜', '신비', '내면의목소리', '은비적지식'],
    keywordsDown: ['비밀', '거리낌', '내면무시', '감정억압'],
    meaningUp: '내면의 목소리에 귀를 기울이세요. 답은 이미 당신 안에 있어요.',
    meaningDown: '직감을 무시하고 있어요. 마음의 소리를 외면하지 마세요.',
    loveAdvice: '상대방의 숨겨진 감정을 직감적으로 느낄 수 있어요. 내면의 목소리를 신뢰하세요.',
    careerAdvice: '표면적인 정보 너머를 보는 통찰력이 필요해요. 직감을 무시하지 마세요.',
    moneyAdvice: '투자나 재무 결정에서 직관이 작동할 수 있어요. 하지만 너무 감정적이지 않도록 주의하세요.',
  },
  {
    id: 3, slug: 'empress', name: '여황제', nameEn: 'The Empress', symbol: '👑',
    element: '흙', planet: '금성',
    keywordsUp: ['풍요', '모성', '창조', '자연', '성장'],
    keywordsDown: ['과잉보호', '의존', '창조력부족', '나태'],
    meaningUp: '풍요와 성장의 에너지가 가득해요. 당신의 노력이 열매를 맺을 거예요.',
    meaningDown: '스스로를 돌보는 것을 소홀히 하고 있어요. 자신에게도 너그러워지세요.',
    loveAdvice: '사랑과 애정이 넘치는 시기예요. 관계가 풍요롭게 성장할 수 있어요.',
    careerAdvice: '창의력과 양육의 에너지가 강해요. 새로운 아이디어나 프로젝트를 키워보세요.',
    moneyAdvice: '재물이 풍족해질 수 있는 시기예요. 자연스러운 흐름을 믿으세요.',
  },
  {
    id: 4, slug: 'emperor', name: '황제', nameEn: 'The Emperor', symbol: '🏛️',
    element: '불', planet: '화성',
    keywordsUp: ['권위', '안정', '리더십', '구조', '아버지상'],
    keywordsDown: ['독재', '완고함', '통제력과도', '유연성부족'],
    meaningUp: '질서와 안정이 필요한 시기예요. 체계적으로 계획을 세워보세요.',
    meaningDown: '너무 경직되어 있어요. 조금 더 유연해질 필요가 있어요.',
    loveAdvice: '안정적이고 구조적인 관계를 원하는 시기예요. 책임감을 보여주세요.',
    careerAdvice: '리더십을 발휘할 때예요. 체계적인 계획과 결단력이 성공의 열쇠예요.',
    moneyAdvice: '재정 관리를 체계적으로 해야 해요. 예산을 세우고 규율을 지키세요.',
  },
  {
    id: 5, slug: 'hierophant', name: '교황', nameEn: 'The Hierophant', symbol: '⛪',
    element: '흙', planet: '목성',
    keywordsUp: ['전통', '가르침', '신앙', '의식', '멘토'],
    keywordsDown: ['구습', '권위주의', '반항', '비전통적'],
    meaningUp: '좋은 스승이나 멘토를 만날 수 있는 시기예요. 배움에 열려있으세요.',
    meaningDown: '전통에 얽매여 있어요. 때로는 새로운 방식을 시도해보세요.',
    loveAdvice: '전통적인 가치나 공식적인 약속이 중요한 시기예요. 가족의 조언을 구해보세요.',
    careerAdvice: '멘토나 선배의 가르침이 도움이 될 거예요. 기존 시스템 안에서 성장하세요.',
    moneyAdvice: '안정적인 재테크 방식을 따르세요. 검증된 방법이 가장 안전해요.',
  },
  {
    id: 6, slug: 'lovers', name: '연인', nameEn: 'The Lovers', symbol: '💕',
    element: '공기', planet: '수성',
    keywordsUp: ['사랑', '선택', '조화', '매력', '결합'],
    keywordsDown: ['갈등', '선택의어려움', '불화', '가치관충돌'],
    meaningUp: '중요한 선택의 순간이에요. 마음이 이끄는 대로 선택하세요.',
    meaningDown: '마음과 이성이 충돌하고 있어요. 진정으로 원하는 것을 스스로에게 물어보세요.',
    loveAdvice: '깊은 사랑과 연결의 에너지예요. 중요한 관계의 선택을 앞두고 있다면 마음을 따르세요.',
    careerAdvice: '협력이나 파트너십이 중요한 시기예요. 올바른 선택이 성공의 열쇠예요.',
    moneyAdvice: '재무적 선택의 기로에 서 있을 수 있어요. 가치관에 맞는 선택을 하세요.',
  },
  {
    id: 7, slug: 'chariot', name: '전차', nameEn: 'The Chariot', symbol: '⚡',
    element: '물', planet: '달',
    keywordsUp: ['승리', '결단', '전진', '의지', '성취'],
    keywordsDown: ['패배감', '방향상실', '조급함', '통제력상실'],
    meaningUp: '강한 의지로 목표를 향해 전진할 때예요. 승리는 가까워요.',
    meaningDown: '방향을 잃은 것 같아요. 잠시 멈춰서 목표를 재정립하세요.',
    loveAdvice: '관계에서 주도권을 잡고 나아가야 해요. 적극적인 행동이 좋은 결과를 가져올 거예요.',
    careerAdvice: '승리와 성취의 카드예요. 강한 의지력으로 목표를 향해 전진하세요.',
    moneyAdvice: '재무 목표를 향해 강하게 밀고 나가세요. 성과가 따라올 거예요.',
  },
  {
    id: 8, slug: 'strength', name: '힘', nameEn: 'Strength', symbol: '🦁',
    element: '불', planet: '태양',
    keywordsUp: ['용기', '인내', '내면의힘', '자제력', '연민'],
    keywordsDown: ['나약함', '자신감결핍', '분노', '두려움'],
    meaningUp: '부드러운 힘이 필요한 시기예요. 인내와 용기로 극복할 수 있어요.',
    meaningDown: '자신감이 떨어져 있어요. 작은 성공부터 다시 쌓아가세요.',
    loveAdvice: '인내심과 따뜻함으로 관계를 풀어가야 해요. 부드러운 힘이 강한 힘이에요.',
    careerAdvice: '내면의 강인함으로 어려움을 이겨낼 수 있어요. 인내하면 승리가 따라와요.',
    moneyAdvice: '재정적 어려움을 인내로 극복할 수 있어요. 자제력을 발휘하세요.',
  },
  {
    id: 9, slug: 'hermit', name: '은둔자', nameEn: 'The Hermit', symbol: '🏔️',
    element: '흙', planet: '수성',
    keywordsUp: ['성찰', '고독', '지혜', '내면탐구', '안내자'],
    keywordsDown: ['고립', '회피', '외로움', '과도한은둔'],
    meaningUp: '혼자만의 시간이 필요해요. 내면을 깊이 들여다보며 답을 찾으세요.',
    meaningDown: '세상과 너무 단절되어 있어요. 적당한 교류도 필요해요.',
    loveAdvice: '관계에 대해 깊이 성찰할 시간이 필요해요. 혼자만의 시간이 답을 줄 거예요.',
    careerAdvice: '혼자 집중하는 시간이 실력 향상의 열쇠예요. 깊이 있는 학습이 필요해요.',
    moneyAdvice: '재정에 대해 깊이 생각해볼 시간이 필요해요. 충동적인 소비를 피하세요.',
  },
  {
    id: 10, slug: 'wheel-of-fortune', name: '운명의 수레바퀴', nameEn: 'Wheel of Fortune', symbol: '🎡',
    element: '불', planet: '목성',
    keywordsUp: ['변화', '전환', '운', '기회', '순환'],
    keywordsDown: ['역경', '불운', '저항', '변화에대한두려움'],
    meaningUp: '운이 바뀌고 있어요. 좋은 흐름이 오고 있으니 기회를 잡으세요.',
    meaningDown: '지금은 흔들리는 시기예요. 변화를 받아들이면 곧 좋아질 거예요.',
    loveAdvice: '운명적인 만남이나 관계의 전환점이 다가오고 있어요. 흐름에 맡겨보세요.',
    careerAdvice: '운명의 흐름이 바뀌고 있어요. 좋은 기회가 오면 주저하지 말고 잡으세요.',
    moneyAdvice: '운이 좋아지는 시기예요. 하지만 흐름을 거스르지 마세요.',
  },
  {
    id: 11, slug: 'justice', name: '정의', nameEn: 'Justice', symbol: '⚖️',
    element: '공기', planet: '금성',
    keywordsUp: ['공정', '진실', '균형', '책임', '인과응보'],
    keywordsDown: ['불공정', '편견', '책임회피', '불균형'],
    meaningUp: '정의로운 결과가 따를 거예요. 정직하게 행동하면 좋은 결실이 있어요.',
    meaningDown: '불공정한 상황에 있을 수 있어요. 균형을 되찾기 위해 노력하세요.',
    loveAdvice: '관계에서 공정함과 균형이 필요해요. 양쪽 모두의 입장을 고려하세요.',
    careerAdvice: '공정한 평가를 받을 수 있어요. 정직하게 일한 만큼 결과가 따를 거예요.',
    moneyAdvice: '공정한 거래와 계약이 중요해요. 법적 문제가 있다면 유리하게 풀릴 수 있어요.',
  },
  {
    id: 12, slug: 'hanged-man', name: '매달린 사람', nameEn: 'The Hanged Man', symbol: '🔄',
    element: '물', planet: '해왕성',
    keywordsUp: ['희생', '새관점', '기다림', '내려놓음', '깨달음'],
    keywordsDown: ['지연', '희생강요', '우유부단', '희망고문'],
    meaningUp: '다르게 바라볼 시간이에요. 기다림 속에서 새로운 깨달음을 얻을 거예요.',
    meaningDown: '너무 오래 머뭇거리고 있어요. 결단을 내릴 때가 왔어요.',
    loveAdvice: '관계를 다른 각도에서 바라봐야 해요. 기다림이 필요한 시기예요.',
    careerAdvice: '잠시 멈춰서 관점을 바꿔보세요. 기다림 속에서 새로운 통찰이 올 거예요.',
    moneyAdvice: '지금은 기다림의 시간이에요. 섣부른 결정보다 인내가 필요해요.',
  },
  {
    id: 13, slug: 'death', name: '죽음', nameEn: 'Death', symbol: '🦋',
    element: '물', planet: '명왕성',
    keywordsUp: ['끝과시작', '변환', '해방', '탈바꿈', '재탄생'],
    keywordsDown: ['저항', '변화거부', '집착', '두려움'],
    meaningUp: '하나의 장이 끝나고 새로운 장이 시작돼요. 과거를 내려놓고 변화를 받아들이세요.',
    meaningDown: '변화를 두려워하고 있어요. 놓아야 할 것을 놓아주세요.',
    loveAdvice: '오래된 관계 패턴이 끝나고 새로운 시작이 있어요. 변화를 받아들이세요.',
    careerAdvice: '구시대의 방식을 버리고 새로운 것으로 탈바꿈할 시기예요.',
    moneyAdvice: '재정적으로 한 시기를 마무리하고 새로운 접근이 필요해요.',
  },
  {
    id: 14, slug: 'temperance', name: '절제', nameEn: 'Temperance', symbol: '🏺',
    element: '불', planet: '목성',
    keywordsUp: ['균형', '조화', '인내', '중용', '치유'],
    keywordsDown: ['과잉', '불균형', '급진', '극단'],
    meaningUp: '모든 것의 균형이 필요한 시기예요. 극단을 피하고 중용을 지키세요.',
    meaningDown: '모든 것을 너무 몰아가고 있어요. 템포를 조절하세요.',
    loveAdvice: '관계에서 조화와 균형이 필요해요. 서로의 차이를 조화롭게 맞춰가세요.',
    careerAdvice: '업무와 휴식의 균형을 찾아야 해요. 조급해하지 말고 차분하게 진행하세요.',
    moneyAdvice: '소비와 저축의 균형이 필요해요. 과도한 지출을 피하세요.',
  },
  {
    id: 15, slug: 'devil', name: '악마', nameEn: 'The Devil', symbol: '😈',
    element: '흙', planet: '토성',
    keywordsUp: ['집착', '유혹', '속박', '그림자', '물질주의'],
    keywordsDown: ['해방', '깨어남', '속박에서벗어남', '자유'],
    meaningUp: '무언가에 지나치게 집착하고 있을 수 있어요. 스스로를 옭아매는 것에서 벗어나세요.',
    meaningDown: '속박에서 벗어날 힘이 생기고 있어요. 자유가 가까워요.',
    loveAdvice: '건강하지 못한 집착이나 의존을 돌아보세요. 자유로운 사랑이 필요해요.',
    careerAdvice: '물질적 성취에만 집착하지 마세요. 진정한 가치가 무엇인지 돌아보세요.',
    moneyAdvice: '물욕이나 과소비의 유혹에 주의하세요. 돈에 대한 건강한 관계가 필요해요.',
  },
  {
    id: 16, slug: 'tower', name: '탑', nameEn: 'The Tower', symbol: '🗼',
    element: '불', planet: '화성',
    keywordsUp: ['급변', '파괴', '진실노출', '해방', '각성'],
    keywordsDown: ['재난회피', '변화지연', '거부', '공포'],
    meaningUp: '갑작스러운 변화가 찾아올 수 있어요. 하지만 무너진 자리에 더 강한 것이 세워질 거예요.',
    meaningDown: '피할 수 없는 변화를 거부하고 있어요. 받아들이면 오히려 성장의 기회가 돼요.',
    loveAdvice: '관계에 갑작스러운 충격이 올 수 있어요. 하지만 진실이 드러나면 더 단단해질 거예요.',
    careerAdvice: '예상치 못한 변화가 찾아올 수 있어요. 무너진 것 위에 더 나은 것을 세울 기회예요.',
    moneyAdvice: '재정적 충격이 있을 수 있어요. 하지만 이것이 더 나은 재정 구조를 만드는 계기가 될 거예요.',
  },
  {
    id: 17, slug: 'star', name: '별', nameEn: 'The Star', symbol: '⭐',
    element: '공기', planet: '천왕성',
    keywordsUp: ['희망', '영감', '치유', '신앙', '밝은미래'],
    keywordsDown: ['절망', '신뢰상실', '방향감각상실', '희망고문'],
    meaningUp: '희망의 빛이 비치고 있어요. 어려움 속에서도 빛은 항상 있어요.',
    meaningDown: '희망을 잃지 마세요. 가장 어두운 밤이 지나면 새벽이 와요.',
    loveAdvice: '희망과 영감이 가득한 관계의 시기예요. 밝은 미래를 믿으세요.',
    careerAdvice: '영감과 비전이 떠오르는 시기예요. 꿈을 믿고 나아가세요.',
    moneyAdvice: '재정적 회복의 빛이 보이고 있어요. 희망을 잃지 마세요.',
  },
  {
    id: 18, slug: 'moon', name: '달', nameEn: 'The Moon', symbol: '🌕',
    element: '물', planet: '해왕성',
    keywordsUp: ['환상', '직관', '무의식', '불안', '신비'],
    keywordsDown: ['혼란해소', '진실노출', '두려움극복', '명확해짐'],
    meaningUp: '상황이 불명확하고 혼란스러울 수 있어요. 시간이 지나면 진실이 드러날 거예요.',
    meaningDown: '혼란이 걷히고 있어요. 진실을 마주할 준비가 되셨나요?',
    loveAdvice: '관계에 불확실성이나 숨겨진 것이 있을 수 있어요. 직관을 믿고 진실을 기다리세요.',
    careerAdvice: '상황이 명확하지 않을 수 있어요. 섣부른 판단을 피하고 더 많은 정보를 기다리세요.',
    moneyAdvice: '재정 상황이 불분명할 수 있어요. 투명한 확인이 필요해요.',
  },
  {
    id: 19, slug: 'sun', name: '태양', nameEn: 'The Sun', symbol: '☀️',
    element: '불', planet: '태양',
    keywordsUp: ['성공', '기쁨', '활력', '긍정', '명확함'],
    keywordsDown: ['일시적침체', '자만', '과도한낙관', '에너지저하'],
    meaningUp: '밝은 에너지가 가득해요! 지금 하는 일이 좋은 결과를 맺을 거예요.',
    meaningDown: '조금 지쳐있을 수 있어요. 에너지를 재충전할 시간이 필요해요.',
    loveAdvice: '관계가 환하고 행복한 시기예요! 서로의 빛이 되어주세요.',
    careerAdvice: '성공과 인정의 시기예요! 당신의 노력이 빛을 발할 거예요.',
    moneyAdvice: '재정적으로 풍요롭고 밝은 시기예요. 수익이 늘어날 수 있어요.',
  },
  {
    id: 20, slug: 'judgement', name: '심판', nameEn: 'Judgement', symbol: '📯',
    element: '불', planet: '명왕성',
    keywordsUp: ['부활', '각성', '소명', '자기평가', '새출발'],
    keywordsDown: ['자기의심', '후회', '과거집착', '변화거부'],
    meaningUp: '인생의 전환점이에요. 과거를 되돌아보고 새로운 소명을 따르세요.',
    meaningDown: '과거에 얽매여 있어요. 자신을 용서하고 앞으로 나아가세요.',
    loveAdvice: '관계의 중요한 전환점이에요. 과거를 정리하고 새로운 단계로 나아가세요.',
    careerAdvice: '커리어의 새로운 소명을 발견할 수 있어요. 자신을 재평가하고 결단하세요.',
    moneyAdvice: '재정 상황을 재평가할 시기예요. 과거의 실수에서 배우고 새로운 계획을 세우세요.',
  },
  {
    id: 21, slug: 'world', name: '세계', nameEn: 'The World', symbol: '🌍',
    element: '흙', planet: '토성',
    keywordsUp: ['완성', '성취', '통합', '여행', '순환완료'],
    keywordsDown: ['미완성', '지연', '마무리부족', '결핍감'],
    meaningUp: '하나의 큰 순환이 완성되고 있어요. 지금까지의 노력이 아름답게 완성될 거예요.',
    meaningDown: '아직 끝내지 못한 일이 있어요. 마지막 한 걸음을 내디뎌보세요.',
    loveAdvice: '관계가 완성과 통합의 단계에 있어요. 깊은 결합과 안정이 찾아와요.',
    careerAdvice: '큰 목표를 성취하고 완성하는 시기예요! 축하받아 마땅한 순간이에요.',
    moneyAdvice: '재정적 목표를 달성하는 시기예요. 성취의 기쁨을 누리세요.',
  },
];

/** Get card by slug */
export function getCardBySlug(slug) {
  return MAJOR_ARCANA.find((c) => c.slug === slug);
}

/** Get next card (wraps around) */
export function getNextCard(id) {
  const nextId = (id + 1) % MAJOR_ARCANA.length;
  return MAJOR_ARCANA.find((c) => c.id === nextId);
}

/** Get previous card (wraps around) */
export function getPrevCard(id) {
  const prevId = (id - 1 + MAJOR_ARCANA.length) % MAJOR_ARCANA.length;
  return MAJOR_ARCANA.find((c) => c.id === prevId);
}
