/**
 * Major Arcana card data for static HTML page generation.
 *
 * Source of truth for card interpretation pages served on GitHub Pages.
 * Data mirrors backend/src/tarotData.ts MAJOR_ARCANA, enriched with
 * slugs, element/planet associations, and love/career/money themes
 * for SEO-rich content pages.
 */

export const MAJOR_ARCANA = [
  {
    id: 0, slug: 'fool', name: '바보', nameEn: 'The Fool', symbol: '🃏',
    element: '공기', planet: '천왕성',
    keywordsUp: ['새시작', '자유', '모험', '순수', '무한한가능성'],
    keywordsDown: ['무모함', '경솔', '미숙', '판단부족'],
    meaningUp: '새로운 시작과 무한한 가능성이 열려있어요. 두려움 없이 한 걸음 내디뎌보세요.',
    meaningDown: '너무 서두르고 있을 수 있어요. 한 박자 쉬어가며 신중하게 결정하세요.',
    loveAdvice: '새로운 인연이나 관계의 새로운 단계를 의미해요. 솔직하고 순수한 마음으로 다가가보세요.',
    careerAdvice: '새로운 프로젝트나 이직의 기회가 있어요. 도전을 두려워하지 마세요.',
    moneyAdvice: '새로운 투자나 수입 경로가 열릴 수 있어요. 다만 너무 무모한 결정은 피하세요.',
  },
  {
    id: 1, slug: 'magician', name: '마법사', nameEn: 'The Magician', symbol: '🧙',
    element: '공기', planet: '수성',
    keywordsUp: ['창조', '기술', '의지력', '집중', '성공'],
    keywordsDown: ['조작', '기만', '재능낭비', '자신감부족'],
    meaningUp: '당신에게 필요한 모든 것이 이미 갖춰져 있어요. 능력을 믿고 행동하세요.',
    meaningDown: '재능을 제대로 활용하지 못하고 있어요. 자신감을 되찾을 시간이에요.',
    loveAdvice: '당신의 매력과 능력이 빛나는 시기예요. 주도적으로 다가가보세요.',
    careerAdvice: '필요한 기술과 자원이 모두 있어요. 자신감을 가지고 추진하면 성공할 수 있어요.',
    moneyAdvice: '돈을 만들어낼 수 있는 능력이 있어요. 아이디어를 실행에 옮겨보세요.',
  },
  {
    id: 2, slug: 'high-priestess', name: '여사제', nameEn: 'The High Priestess', symbol: '🌙',
    element: '물', planet: '달',
    keywordsUp: ['직관', '지혜', '신비', '내면의목소리', '은비적지식'],
    keywordsDown: ['비밀', '거리낌', '내면무시', '감정억압'],
    meaningUp: '내면의 목소리에 귀를 기울이세요. 답은 이미 당신 안에 있어요.',
    meaningDown: '직감을 무시하고 있어요. 마음의 소리를 외면하지 마세요.',
    loveAdvice: '상대방의 숨겨진 감정을 직감적으로 느낄 수 있어요. 내면의 목소리를 신뢰하세요.',
    careerAdvice: '표면적인 정보 너머를 보는 통찰력이 필요해요. 직감을 무시하지 마세요.',
    moneyAdvice: '투자나 재무 결정에서 직관이 작동할 수 있어요. 하지만 너무 감정적이지 않도록 주의하세요.',
  },
  {
    id: 3, slug: 'empress', name: '여황제', nameEn: 'The Empress', symbol: '👑',
    element: '흙', planet: '금성',
    keywordsUp: ['풍요', '모성', '창조', '자연', '성장'],
    keywordsDown: ['과잉보호', '의존', '창조력부족', '나태'],
    meaningUp: '풍요와 성장의 에너지가 가득해요. 당신의 노력이 열매를 맺을 거예요.',
    meaningDown: '스스로를 돌보는 것을 소홀히 하고 있어요. 자신에게도 너그러워지세요.',
    loveAdvice: '사랑과 애정이 넘치는 시기예요. 관계가 풍요롭게 성장할 수 있어요.',
    careerAdvice: '창의력과 양육의 에너지가 강해요. 새로운 아이디어나 프로젝트를 키워보세요.',
    moneyAdvice: '재물이 풍족해질 수 있는 시기예요. 자연스러운 흐름을 믿으세요.',
  },
  {
    id: 4, slug: 'emperor', name: '황제', nameEn: 'The Emperor', symbol: '🏛️',
    element: '불', planet: '화성',
    keywordsUp: ['권위', '안정', '리더십', '구조', '아버지상'],
    keywordsDown: ['독재', '완고함', '통제력과도', '유연성부족'],
    meaningUp: '질서와 안정이 필요한 시기예요. 체계적으로 계획을 세워보세요.',
    meaningDown: '너무 경직되어 있어요. 조금 더 유연해질 필요가 있어요.',
    loveAdvice: '안정적이고 구조적인 관계를 원하는 시기예요. 책임감을 보여주세요.',
    careerAdvice: '리더십을 발휘할 때예요. 체계적인 계획과 결단력이 성공의 열쇠예요.',
    moneyAdvice: '재정 관리를 체계적으로 해야 해요. 예산을 세우고 규율을 지키세요.',
  },
  {
    id: 5, slug: 'hierophant', name: '교황', nameEn: 'The Hierophant', symbol: '⛪',
    element: '흙', planet: '목성',
    keywordsUp: ['전통', '가르침', '신앙', '의식', '멘토'],
    keywordsDown: ['구습', '권위주의', '반항', '비전통적'],
    meaningUp: '좋은 스승이나 멘토를 만날 수 있는 시기예요. 배움에 열려있으세요.',
    meaningDown: '전통에 얽매여 있어요. 때로는 새로운 방식을 시도해보세요.',
    loveAdvice: '전통적인 가치나 공식적인 약속이 중요한 시기예요. 가족의 조언을 구해보세요.',
    careerAdvice: '멘토나 선배의 가르침이 도움이 될 거예요. 기존 시스템 안에서 성장하세요.',
    moneyAdvice: '안정적인 재테크 방식을 따르세요. 검증된 방법이 가장 안전해요.',
  },
  {
    id: 6, slug: 'lovers', name: '연인', nameEn: 'The Lovers', symbol: '💕',
    element: '공기', planet: '수성',
    keywordsUp: ['사랑', '선택', '조화', '매력', '결합'],
    keywordsDown: ['갈등', '선택의어려움', '불화', '가치관충돌'],
    meaningUp: '중요한 선택의 순간이에요. 마음이 이끄는 대로 선택하세요.',
    meaningDown: '마음과 이성이 충돌하고 있어요. 진정으로 원하는 것을 스스로에게 물어보세요.',
    loveAdvice: '깊은 사랑과 연결의 에너지예요. 중요한 관계의 선택을 앞두고 있다면 마음을 따르세요.',
    careerAdvice: '협력이나 파트너십이 중요한 시기예요. 올바른 선택이 성공의 열쇠예요.',
    moneyAdvice: '재무적 선택의 기로에 서 있을 수 있어요. 가치관에 맞는 선택을 하세요.',
  },
  {
    id: 7, slug: 'chariot', name: '전차', nameEn: 'The Chariot', symbol: '⚡',
    element: '물', planet: '달',
    keywordsUp: ['승리', '결단', '전진', '의지', '성취'],
    keywordsDown: ['패배감', '방향상실', '조급함', '통제력상실'],
    meaningUp: '강한 의지로 목표를 향해 전진할 때예요. 승리는 가까워요.',
    meaningDown: '방향을 잃은 것 같아요. 잠시 멈춰서 목표를 재정립하세요.',
    loveAdvice: '관계에서 주도권을 잡고 나아가야 해요. 적극적인 행동이 좋은 결과를 가져올 거예요.',
    careerAdvice: '승리와 성취의 카드예요. 강한 의지력으로 목표를 향해 전진하세요.',
    moneyAdvice: '재무 목표를 향해 강하게 밀고 나가세요. 성과가 따라올 거예요.',
  },
  {
    id: 8, slug: 'strength', name: '힘', nameEn: 'Strength', symbol: '🦁',
    element: '불', planet: '태양',
    keywordsUp: ['용기', '인내', '내면의힘', '자제력', '연민'],
    keywordsDown: ['나약함', '자신감결핍', '분노', '두려움'],
    meaningUp: '부드러운 힘이 필요한 시기예요. 인내와 용기로 극복할 수 있어요.',
    meaningDown: '자신감이 떨어져 있어요. 작은 성공부터 다시 쌓아가세요.',
    loveAdvice: '인내심과 따뜻함으로 관계를 풀어가야 해요. 부드러운 힘이 강한 힘이에요.',
    careerAdvice: '내면의 강인함으로 어려움을 이겨낼 수 있어요. 인내하면 승리가 따라와요.',
    moneyAdvice: '재정적 어려움을 인내로 극복할 수 있어요. 자제력을 발휘하세요.',
  },
  {
    id: 9, slug: 'hermit', name: '은둔자', nameEn: 'The Hermit', symbol: '🏔️',
    element: '흙', planet: '수성',
    keywordsUp: ['성찰', '고독', '지혜', '내면탐구', '안내자'],
    keywordsDown: ['고립', '회피', '외로움', '과도한은둔'],
    meaningUp: '혼자만의 시간이 필요해요. 내면을 깊이 들여다보며 답을 찾으세요.',
    meaningDown: '세상과 너무 단절되어 있어요. 적당한 교류도 필요해요.',
    loveAdvice: '관계에 대해 깊이 성찰할 시간이 필요해요. 혼자만의 시간이 답을 줄 거예요.',
    careerAdvice: '혼자 집중하는 시간이 실력 향상의 열쇠예요. 깊이 있는 학습이 필요해요.',
    moneyAdvice: '재정에 대해 깊이 생각해볼 시간이 필요해요. 충동적인 소비를 피하세요.',
  },
  {
    id: 10, slug: 'wheel-of-fortune', name: '운명의 수레바퀴', nameEn: 'Wheel of Fortune', symbol: '🎡',
    element: '불', planet: '목성',
    keywordsUp: ['변화', '전환', '운', '기회', '순환'],
    keywordsDown: ['역경', '불운', '저항', '변화에대한두려움'],
    meaningUp: '운이 바뀌고 있어요. 좋은 흐름이 오고 있으니 기회를 잡으세요.',
    meaningDown: '지금은 흔들리는 시기예요. 변화를 받아들이면 곧 좋아질 거예요.',
    loveAdvice: '운명적인 만남이나 관계의 전환점이 다가오고 있어요. 흐름에 맡겨보세요.',
    careerAdvice: '운명의 흐름이 바뀌고 있어요. 좋은 기회가 오면 주저하지 말고 잡으세요.',
    moneyAdvice: '운이 좋아지는 시기예요. 하지만 흐름을 거스르지 마세요.',
  },
  {
    id: 11, slug: 'justice', name: '정의', nameEn: 'Justice', symbol: '⚖️',
    element: '공기', planet: '금성',
    keywordsUp: ['공정', '진실', '균형', '책임', '인과응보'],
    keywordsDown: ['불공정', '편견', '책임회피', '불균형'],
    meaningUp: '정의로운 결과가 따를 거예요. 정직하게 행동하면 좋은 결실이 있어요.',
    meaningDown: '불공정한 상황에 있을 수 있어요. 균형을 되찾기 위해 노력하세요.',
    loveAdvice: '관계에서 공정함과 균형이 필요해요. 양쪽 모두의 입장을 고려하세요.',
    careerAdvice: '공정한 평가를 받을 수 있어요. 정직하게 일한 만큼 결과가 따를 거예요.',
    moneyAdvice: '공정한 거래와 계약이 중요해요. 법적 문제가 있다면 유리하게 풀릴 수 있어요.',
  },
  {
    id: 12, slug: 'hanged-man', name: '매달린 사람', nameEn: 'The Hanged Man', symbol: '🔄',
    element: '물', planet: '해왕성',
    keywordsUp: ['희생', '새관점', '기다림', '내려놓음', '깨달음'],
    keywordsDown: ['지연', '희생강요', '우유부단', '희망고문'],
    meaningUp: '다르게 바라볼 시간이에요. 기다림 속에서 새로운 깨달음을 얻을 거예요.',
    meaningDown: '너무 오래 머뭇거리고 있어요. 결단을 내릴 때가 왔어요.',
    loveAdvice: '관계를 다른 각도에서 바라봐야 해요. 기다림이 필요한 시기예요.',
    careerAdvice: '잠시 멈춰서 관점을 바꿔보세요. 기다림 속에서 새로운 통찰이 올 거예요.',
    moneyAdvice: '지금은 기다림의 시간이에요. 섣부른 결정보다 인내가 필요해요.',
  },
  {
    id: 13, slug: 'death', name: '죽음', nameEn: 'Death', symbol: '🦋',
    element: '물', planet: '명왕성',
    keywordsUp: ['끝과시작', '변환', '해방', '탈바꿈', '재탄생'],
    keywordsDown: ['저항', '변화거부', '집착', '두려움'],
    meaningUp: '하나의 장이 끝나고 새로운 장이 시작돼요. 과거를 내려놓고 변화를 받아들이세요.',
    meaningDown: '변화를 두려워하고 있어요. 놓아야 할 것을 놓아주세요.',
    loveAdvice: '오래된 관계 패턴이 끝나고 새로운 시작이 있어요. 변화를 받아들이세요.',
    careerAdvice: '구시대의 방식을 버리고 새로운 것으로 탈바꿈할 시기예요.',
    moneyAdvice: '재정적으로 한 시기를 마무리하고 새로운 접근이 필요해요.',
  },
  {
    id: 14, slug: 'temperance', name: '절제', nameEn: 'Temperance', symbol: '🏺',
    element: '불', planet: '목성',
    keywordsUp: ['균형', '조화', '인내', '중용', '치유'],
    keywordsDown: ['과잉', '불균형', '급진', '극단'],
    meaningUp: '모든 것의 균형이 필요한 시기예요. 극단을 피하고 중용을 지키세요.',
    meaningDown: '모든 것을 너무 몰아가고 있어요. 템포를 조절하세요.',
    loveAdvice: '관계에서 조화와 균형이 필요해요. 서로의 차이를 조화롭게 맞춰가세요.',
    careerAdvice: '업무와 휴식의 균형을 찾아야 해요. 조급해하지 말고 차분하게 진행하세요.',
    moneyAdvice: '소비와 저축의 균형이 필요해요. 과도한 지출을 피하세요.',
  },
  {
    id: 15, slug: 'devil', name: '악마', nameEn: 'The Devil', symbol: '😈',
    element: '흙', planet: '토성',
    keywordsUp: ['집착', '유혹', '속박', '그림자', '물질주의'],
    keywordsDown: ['해방', '깨어남', '속박에서벗어남', '자유'],
    meaningUp: '무언가에 지나치게 집착하고 있을 수 있어요. 스스로를 옭아매는 것에서 벗어나세요.',
    meaningDown: '속박에서 벗어날 힘이 생기고 있어요. 자유가 가까워요.',
    loveAdvice: '건강하지 못한 집착이나 의존을 돌아보세요. 자유로운 사랑이 필요해요.',
    careerAdvice: '물질적 성취에만 집착하지 마세요. 진정한 가치가 무엇인지 돌아보세요.',
    moneyAdvice: '물욕이나 과소비의 유혹에 주의하세요. 돈에 대한 건강한 관계가 필요해요.',
  },
  {
    id: 16, slug: 'tower', name: '탑', nameEn: 'The Tower', symbol: '🗼',
    element: '불', planet: '화성',
    keywordsUp: ['급변', '파괴', '진실노출', '해방', '각성'],
    keywordsDown: ['재난회피', '변화지연', '거부', '공포'],
    meaningUp: '갑작스러운 변화가 찾아올 수 있어요. 하지만 무너진 자리에 더 강한 것이 세워질 거예요.',
    meaningDown: '피할 수 없는 변화를 거부하고 있어요. 받아들이면 오히려 성장의 기회가 돼요.',
    loveAdvice: '관계에 갑작스러운 충격이 올 수 있어요. 하지만 진실이 드러나면 더 단단해질 거예요.',
    careerAdvice: '예상치 못한 변화가 찾아올 수 있어요. 무너진 것 위에 더 나은 것을 세울 기회예요.',
    moneyAdvice: '재정적 충격이 있을 수 있어요. 하지만 이것이 더 나은 재정 구조를 만드는 계기가 될 거예요.',
  },
  {
    id: 17, slug: 'star', name: '별', nameEn: 'The Star', symbol: '⭐',
    element: '공기', planet: '천왕성',
    keywordsUp: ['희망', '영감', '치유', '신앙', '밝은미래'],
    keywordsDown: ['절망', '신뢰상실', '방향감각상실', '희망고문'],
    meaningUp: '희망의 빛이 비치고 있어요. 어려움 속에서도 빛은 항상 있어요.',
    meaningDown: '희망을 잃지 마세요. 가장 어두운 밤이 지나면 새벽이 와요.',
    loveAdvice: '희망과 영감이 가득한 관계의 시기예요. 밝은 미래를 믿으세요.',
    careerAdvice: '영감과 비전이 떠오르는 시기예요. 꿈을 믿고 나아가세요.',
    moneyAdvice: '재정적 회복의 빛이 보이고 있어요. 희망을 잃지 마세요.',
  },
  {
    id: 18, slug: 'moon', name: '달', nameEn: 'The Moon', symbol: '🌕',
    element: '물', planet: '해왕성',
    keywordsUp: ['환상', '직관', '무의식', '불안', '신비'],
    keywordsDown: ['혼란해소', '진실노출', '두려움극복', '명확해짐'],
    meaningUp: '상황이 불명확하고 혼란스러울 수 있어요. 시간이 지나면 진실이 드러날 거예요.',
    meaningDown: '혼란이 걷히고 있어요. 진실을 마주할 준비가 되셨나요?',
    loveAdvice: '관계에 불확실성이나 숨겨진 것이 있을 수 있어요. 직관을 믿고 진실을 기다리세요.',
    careerAdvice: '상황이 명확하지 않을 수 있어요. 섣부른 판단을 피하고 더 많은 정보를 기다리세요.',
    moneyAdvice: '재정 상황이 불분명할 수 있어요. 투명한 확인이 필요해요.',
  },
  {
    id: 19, slug: 'sun', name: '태양', nameEn: 'The Sun', symbol: '☀️',
    element: '불', planet: '태양',
    keywordsUp: ['성공', '기쁨', '활력', '긍정', '명확함'],
    keywordsDown: ['일시적침체', '자만', '과도한낙관', '에너지저하'],
    meaningUp: '밝은 에너지가 가득해요! 지금 하는 일이 좋은 결과를 맺을 거예요.',
    meaningDown: '조금 지쳐있을 수 있어요. 에너지를 재충전할 시간이 필요해요.',
    loveAdvice: '관계가 환하고 행복한 시기예요! 서로의 빛이 되어주세요.',
    careerAdvice: '성공과 인정의 시기예요! 당신의 노력이 빛을 발할 거예요.',
    moneyAdvice: '재정적으로 풍요롭고 밝은 시기예요. 수익이 늘어날 수 있어요.',
  },
  {
    id: 20, slug: 'judgement', name: '심판', nameEn: 'Judgement', symbol: '📯',
    element: '불', planet: '명왕성',
    keywordsUp: ['부활', '각성', '소명', '자기평가', '새출발'],
    keywordsDown: ['자기의심', '후회', '과거집착', '변화거부'],
    meaningUp: '인생의 전환점이에요. 과거를 되돌아보고 새로운 소명을 따르세요.',
    meaningDown: '과거에 얽매여 있어요. 자신을 용서하고 앞으로 나아가세요.',
    loveAdvice: '관계의 중요한 전환점이에요. 과거를 정리하고 새로운 단계로 나아가세요.',
    careerAdvice: '커리어의 새로운 소명을 발견할 수 있어요. 자신을 재평가하고 결단하세요.',
    moneyAdvice: '재정 상황을 재평가할 시기예요. 과거의 실수에서 배우고 새로운 계획을 세우세요.',
  },
  {
    id: 21, slug: 'world', name: '세계', nameEn: 'The World', symbol: '🌍',
    element: '흙', planet: '토성',
    keywordsUp: ['완성', '성취', '통합', '여행', '순환완료'],
    keywordsDown: ['미완성', '지연', '마무리부족', '결핍감'],
    meaningUp: '하나의 큰 순환이 완성되고 있어요. 지금까지의 노력이 아름답게 완성될 거예요.',
    meaningDown: '아직 끝내지 못한 일이 있어요. 마지막 한 걸음을 내디뎌보세요.',
    loveAdvice: '관계가 완성과 통합의 단계에 있어요. 깊은 결합과 안정이 찾아와요.',
    careerAdvice: '큰 목표를 성취하고 완성하는 시기예요! 축하받아 마땅한 순간이에요.',
    moneyAdvice: '재정적 목표를 달성하는 시기예요. 성취의 기쁨을 누리세요.',
  },
];

/**
 * Minor Arcana card data (56 cards).
 *
 * Enriched with slugs, element/planet (astrological decan rulers and
 * zodiac associations), and love/career/money advice for SEO-rich pages.
 *
 * Suit elements: Cups = 물, Pentacles = 흙, Swords = 공기, Wands = 불
 */
export const MINOR_ARCANA = [
  // ===== Cups (컵) — 감정 · 사랑 · 관계 / element: 물 =====
  { id: 22, slug: 'ace-of-cups', name: '컵 에이스', nameEn: 'Ace of Cups', symbol: '💕', element: '물', planet: '게자리/전갈자리/물고기자리',
    keywordsUp: ['새로운사랑', '감정의홍수', '영적각성', '창조적영감', '은총'],
    keywordsDown: ['감정억제', '사랑거부', '공허함', '창조력막힘'],
    meaningUp: '가슴이 벅차오르는 새로운 감정이 시작되고 있어요. 사랑과 영감의 문이 열렸어요.',
    meaningDown: '감정을 닫아두고 있어요. 마음의 문을 열 용기가 필요해요.',
    loveAdvice: '새로운 사랑의 시작이에요. 마음을 열면 설렘이 가득한 만남이 찾아올 거예요.',
    careerAdvice: '직장에서 영감과 창의성이 샘솟는 시기예요. 감정적으로 몰두할 수 있는 일을 찾아보세요.',
    moneyAdvice: '풍요로운 감정이 물질적 만족으로 이어질 수 있어요. 마음이 이끄는 곳에 투자해보세요.' },
  { id: 23, slug: 'two-of-cups', name: '컵 2', nameEn: 'Two of Cups', symbol: '💕', element: '물', planet: '금성(게자리)',
    keywordsUp: ['파트너십', '상호이해', '매력', '화해', '결합'],
    keywordsDown: ['관계갈등', '이해부족', '이별', '불화'],
    meaningUp: '서로의 마음이 통하는 아름다운 만남이에요. 진정한 파트너십이 시작될 수 있어요.',
    meaningDown: '관계에서 균형이 깨졌어요. 서로의 마음을 다시 들여다볼 시간이에요.',
    loveAdvice: '운명적인 만남이나 관계의 깊어짐을 의미해요. 서로를 향한 마음이 통하고 있어요.',
    careerAdvice: '훌륭한 협력자를 만나거나 동업의 기회가 생길 수 있어요. 신뢰를 바탕으로 함께하세요.',
    moneyAdvice: '재정적으로 이익이 되는 파트너십이나 계약이 성사될 수 있어요.' },
  { id: 24, slug: 'three-of-cups', name: '컵 3', nameEn: 'Three of Cups', symbol: '💕', element: '물', planet: '수성(게자리)',
    keywordsUp: ['축하', '우정', '기쁨', '협력', '소통'],
    keywordsDown: ['과도한즐김', '뒷담화', '배신', '소외감'],
    meaningUp: '좋은 사람들과 함께 기쁨을 나눌 시기예요. 우정과 축하가 가득해요.',
    meaningDown: '관계에서 소외감을 느낄 수 있어요. 진정한 친구에게 먼저 다가가 보세요.',
    loveAdvice: '친구의 소개로 좋은 인연을 만날 수 있어요. 즐거운 자리에서 설렘을 발견하세요.',
    careerAdvice: '팀 동료들과 좋은 관계를 맺을 수 있어요. 협력이 성과로 이어지는 시기예요.',
    moneyAdvice: '지인을 통한 수익 기회가 있을 수 있어요. 하지만 과소비는 주의하세요.' },
  { id: 25, slug: 'four-of-cups', name: '컵 4', nameEn: 'Four of Cups', symbol: '💕', element: '물', planet: '달(게자리)',
    keywordsUp: ['명상', '내성', '재고', '망설임', '무관심'],
    keywordsDown: ['기회포착', '각성', '새로운관심', '결단'],
    meaningUp: '현재에 만족하지 못하고 무언가 더 바라고 있어요. 잠시 마음을 가라앉히고 진짜 원하는 것을 찾아보세요.',
    meaningDown: '외면했던 기회가 눈에 들어오기 시작했어요. 지금 눈을 뜨면 새로운 가능성이 보여요.',
    loveAdvice: '현재 관계에 무료함을 느낄 수 있어요. 새로운 자극보다는 내면의 욕구를 들여다보세요.',
    careerAdvice: '현재 일에 대한 흥미가 떨어졌어요. 진정으로 원하는 방향인지 성찰할 시간이에요.',
    moneyAdvice: '재정적 기회를 놓치고 있을 수 있어요. 주변의 제안에 더 열린 자세가 필요해요.' },
  { id: 26, slug: 'five-of-cups', name: '컵 5', nameEn: 'Five of Cups', symbol: '💕', element: '물', planet: '화성(전갈자리)',
    keywordsUp: ['상실', '후회', '슬픔', '실망', '과거집착'],
    keywordsDown: ['수용', '회복', '전진', '남은것감사'],
    meaningUp: '잃어버린 것 때문에 슬퍼하고 있어요. 하지만 아직 남아있는 소중한 것들을 바라봐요.',
    meaningDown: '슬픔에서 서서히 벗어나고 있어요. 앞을 향해 나아갈 힘이 생기고 있어요.',
    loveAdvice: '이별이나 실연의 아픔이 있을 수 있어요. 하지만 남아있는 사랑을 바라보세요.',
    careerAdvice: '직장에서의 실망감이 클 수 있어요. 잃어버린 것보다 남은 가능성에 집중하세요.',
    moneyAdvice: '재정적 손실로 우울할 수 있어요. 하지만 아직 복구할 수 있는 자원이 남아있어요.' },
  { id: 27, slug: 'six-of-cups', name: '컵 6', nameEn: 'Six of Cups', symbol: '💕', element: '물', planet: '태양(전갈자리)',
    keywordsUp: ['추억', '순수', '향수', '과거인연', '어린시절'],
    keywordsDown: ['과거집착', '현실도피', '미련', '성장지연'],
    meaningUp: '따뜻한 추억과 순수한 마음이 당신을 감싸요. 과거의 좋은 인연이 다시 이어질 수 있어요.',
    meaningDown: '과거에 너무 머물러 있어요. 아름다운 추억은 간직하되 지금을 살아가세요.',
    loveAdvice: '첫사랑이나 과거의 인연이 다시 떠오를 수 있어요. 순수한 마음이 중요한 시기예요.',
    careerAdvice: '과거의 경험이나 인맥이 지금의 일에 도움이 될 수 있어요. 옛 동료와 연락해보세요.',
    moneyAdvice: '과거의 투자나 노력이 지금 수익으로 돌아올 수 있어요. 하지만 과거 방식에만 의존하지 마세요.' },
  { id: 28, slug: 'seven-of-cups', name: '컵 7', nameEn: 'Seven of Cups', symbol: '💕', element: '물', planet: '금성(전갈자리)',
    keywordsUp: ['선택', '환상', '꿈', '상상력', '다양한기회'],
    keywordsDown: ['현실직시', '명확함', '결단', '환상깨기'],
    meaningUp: '너무 많은 선택지 앞에서 헤매고 있어요. 마음이 진정으로 원하는 것을 구별해내세요.',
    meaningDown: '환상의 안개가 걷히고 있어요. 현실을 직시하고 명확한 결정을 내릴 때예요.',
    loveAdvice: '여러 매력적인 사람 사이에서 고민할 수 있어요. 환상이 아닌 진짜 마음을 구별하세요.',
    careerAdvice: '다양한 커리어 기회가 동시에 다가올 수 있어요. 하나에 집중하기 전에 현실적으로 평가하세요.',
    moneyAdvice: '투자 선택지가 많지만 환상에 빠지지 마세요. 리스크를 냉정하게 분석하세요.' },
  { id: 29, slug: 'eight-of-cups', name: '컵 8', nameEn: 'Eight of Cups', symbol: '💕', element: '물', planet: '토성(물고기자리)',
    keywordsUp: ['이별', '더깊은의미', '내면탐구', '떠남', '성찰'],
    keywordsDown: ['회피중단', '복귀', '현실수용', '용기'],
    meaningUp: '더 이상 의미 없는 것을 뒤로하고 떠날 때예요. 내면이 원하는 더 깊은 곳을 향해 가세요.',
    meaningDown: '도망치고 있는 것인지 스스로에게 물어보세요. 현실에서 답을 찾을 수도 있어요.',
    loveAdvice: '더 이상 만족스럽지 않은 관계를 떠날 용기가 필요해요. 진정한 감정의 충만함을 찾으세요.',
    careerAdvice: '지금의 일이 의미 없게 느껴진다면 새로운 길을 찾을 때예요. 더 깊은 보람을 추구하세요.',
    moneyAdvice: '물질적 안정감보다 내면의 만족이 중요해지는 시기예요. 돈만 좇지 마세요.' },
  { id: 30, slug: 'nine-of-cups', name: '컵 9', nameEn: 'Nine of Cups', symbol: '💕', element: '물', planet: '목성(물고기자리)',
    keywordsUp: ['만족', '소원성취', '감정적풍요', '행복', '자기애'],
    keywordsDown: ['자만', '만족지연', '이기심', '과도한욕심'],
    meaningUp: '마음이 바라던 것이 이루어지는 시기예요. 감정적으로 충만하고 만족스러운 시간이에요.',
    meaningDown: '원하는 것이 채워지지 않아 답답할 수 있어요. 작은 것에 감사하는 연습이 필요해요.',
    loveAdvice: '원하던 사랑이 이루어지는 행복한 시기예요. 관계에서 깊은 만족감을 느낄 거예요.',
    careerAdvice: '커리어 목표를 달성하고 인정받는 만족스러운 시기예요. 성취감을 만끽하세요.',
    moneyAdvice: '재정적 소원이 이루어질 수 있어요. 하지만 자만하지 말고 감사하는 마음을 가지세요.' },
  { id: 31, slug: 'ten-of-cups', name: '컵 10', nameEn: 'Ten of Cups', symbol: '💕', element: '물', planet: '화성(물고기자리)',
    keywordsUp: ['가족', '완전한행복', '조화', '영원한사랑', '안식'],
    keywordsDown: ['가족갈등', '가치충돌', '불화', '이상과현실괴리'],
    meaningUp: '사랑하는 사람들과 깊은 행복을 나누는 시기예요. 마음의 고향을 찾은 듯한 안정감이에요.',
    meaningDown: '관계에서 이상과 현실의 괴리를 느낄 수 있어요. 서로의 다름을 인정하는 대화가 필요해요.',
    loveAdvice: '관계가 꽃피는 시기예요. 가족과 함께하는 깊은 행복과 조화가 가득해요.',
    careerAdvice: '일과 삶의 균형이 완벽한 시기예요. 직장에서 소속감과 안정감을 느낄 거예요.',
    moneyAdvice: '재정적 안정이 가족의 행복으로 이어지는 시기예요. 풍요를 사랑하는 사람들과 나누세요.' },
  { id: 32, slug: 'page-of-cups', name: '컵 시종', nameEn: 'Page of Cups', symbol: '💕', element: '물', planet: '흙(물의흙)',
    keywordsUp: ['직관', '감성', '예술적재능', '순수한메시지', '로맨틱'],
    keywordsDown: ['감정미숙', '변덕', '현실감부족', '과몽상'],
    meaningUp: '예상치 못한 감정의 메시지가 찾아와요. 순수한 마음으로 직관을 따라가 보세요.',
    meaningDown: '감정적으로 아직 미숙해요. 느끼는 것과 행동하는 것 사이의 균형이 필요해요.',
    loveAdvice: '풋풋하고 로맨틱한 감정이 싹트고 있어요. 순수한 마음으로 다가가보세요.',
    careerAdvice: '창의적인 아이디어가 떠오르는 시기예요. 예술적 감각을 살릴 수 있는 일을 찾아보세요.',
    moneyAdvice: '감각과 영감으로 수익 기회를 찾을 수 있어요. 하지만 현실적인 계획도 함께 세우세요.' },
  { id: 33, slug: 'knight-of-cups', name: '컵 기사', nameEn: 'Knight of Cups', symbol: '💕', element: '물', planet: '불(물의불)',
    keywordsUp: ['로맨스', '매력', '이상주의', '예술', '제안'],
    keywordsDown: ['비현실적', '기분파', '허세', '실천력부족'],
    meaningUp: '마음을 따라 움직이는 아름다운 기사가 다가와요. 로맨틱한 제안이나 영감이 찾아올 거예요.',
    meaningDown: '꿈만 크고 행동이 부족해요. 이상을 현실로 옮기는 실천이 필요해요.',
    loveAdvice: '매력적인 사람이 다가오거나 로맨틱한 제안이 있을 수 있어요. 마음을 따라가보세요.',
    careerAdvice: '예술이나 창의적인 분야에서 기회가 찾아와요. 영감을 행동으로 옮기세요.',
    moneyAdvice: '감각적인 투자나 매력적인 제안이 올 수 있어요. 하지만 현실성을 꼭 확인하세요.' },
  { id: 34, slug: 'queen-of-cups', name: '컵 여왕', nameEn: 'Queen of Cups', symbol: '💕', element: '물', planet: '물(물의물)',
    keywordsUp: ['공감', '따뜻함', '직관적지혜', '치유', '헌신'],
    keywordsDown: ['감정기복', '의존성', '과잉흡수', '경계흐림'],
    meaningUp: '따뜻한 공감과 직관의 에너지가 강해요. 누군가에게 큰 위로가 되어줄 수 있어요.',
    meaningDown: '타인의 감정에 너무 깊이 빠져들어요. 자신과 타인의 경계를 구분하세요.',
    loveAdvice: '따뜻하고 헌신적인 사랑을 주고받는 시기예요. 파트너에게 깊은 공감을 보여주세요.',
    careerAdvice: '돌봄이나 상담, 치유 관련 일에서 빛을 발해요. 공감 능력이 최대 강점이에요.',
    moneyAdvice: '직관을 활용한 재정 결정이 유리해요. 하지만 감정적 소비는 주의하세요.' },
  { id: 35, slug: 'king-of-cups', name: '컵 왕', nameEn: 'King of Cups', symbol: '💕', element: '물', planet: '공기(물의공기)',
    keywordsUp: ['감정적성숙', '평온', '외교술', '지혜', '균형'],
    keywordsDown: ['감정억압', '조종', '냉담함', '무책임'],
    meaningUp: '감정을 다스리는 성숙함을 갖추고 있어요. 평온함으로 상황을 풀어나갈 수 있어요.',
    meaningDown: '감정을 억누르고 있어요. 솔직한 마음을 표현하는 것이 오히려 도움이 될 거예요.',
    loveAdvice: '감정적으로 성숙한 관계를 맺을 수 있어요. 평온함과 지혜로 사랑을 이끄세요.',
    careerAdvice: '감정 지능이 뛰어난 리더가 될 수 있어요. 갈등을 부드럽게 중재하는 능력이 빛나요.',
    moneyAdvice: '냉정함과 감성의 균형으로 재정을 관리할 수 있어요. 침착한 판단이 유리해요.' },

  // ===== Pentacles (펜타클) — 물질 · 돈 · 현실 / element: 흙 =====
  { id: 36, slug: 'ace-of-pentacles', name: '펜타클 에이스', nameEn: 'Ace of Pentacles', symbol: '💰', element: '흙', planet: '황소자리/처녀자리/염소자리',
    keywordsUp: ['새기회', '풍요의시작', '투자', '번영', '실현'],
    keywordsDown: ['기회상실', '재무지연', '나태', '계획부족'],
    meaningUp: '물질적 풍요의 새로운 기회가 찾아왔어요. 지금 뿌린 씨앗이 훌륭한 열매를 맺을 거예요.',
    meaningDown: '좋은 기회를 놓칠 수 있어요. 준비가 되어 있는지 점검해보세요.',
    loveAdvice: '안정적이고 신뢰할 수 있는 관계의 시작이에요. 현실적인 기반 위에 사랑을 쌓으세요.',
    careerAdvice: '새로운 일자리나 사업 기회, 승진의 가능성이 열렸어요. 기회를 꼭 잡으세요.',
    moneyAdvice: '재정적 풍요의 시작이에요. 새 투자나 수입 경로가 유망해요. 신중하게 시작하세요.' },
  { id: 37, slug: 'two-of-pentacles', name: '펜타클 2', nameEn: 'Two of Pentacles', symbol: '💰', element: '흙', planet: '목성(황소자리)',
    keywordsUp: ['균형', '융통성', '우선순위', '변화적응', '재주'],
    keywordsDown: ['과부하', '혼란', '우유부단', '조직력부족'],
    meaningUp: '여러 일을 동시에 처리해야 하는 시기예요. 유연하게 균형을 잡으며 해내고 있어요.',
    meaningDown: '너무 많은 것을 한꺼번에 하려고 해요. 우선순위를 정해 하나씩 해나가세요.',
    loveAdvice: '연애와 일 사이에서 균형을 잡아야 해요. 유연한 태도가 관계를 지켜줄 거예요.',
    careerAdvice: '여러 프로젝트를 병행해야 해요. 우선순위를 정하고 시간 관리를 철저히 하세요.',
    moneyAdvice: '수입과 지출의 균형이 중요해요. 예산을 유연하게 조정하면서 관리하세요.' },
  { id: 38, slug: 'three-of-pentacles', name: '펜타클 3', nameEn: 'Three of Pentacles', symbol: '💰', element: '흙', planet: '화성(염소자리)',
    keywordsUp: ['협력', '팀워크', '실력인정', '건설', '전문성'],
    keywordsDown: ['협력부족', '소통문제', '실력과외부평가괴리', '불협화음'],
    meaningUp: '다른 사람들과 협력하여 훌륭한 결과를 만들어낼 수 있어요. 당신의 실력이 인정받는 시기예요.',
    meaningDown: '팀 내에서 의견 충돌이 있을 수 있어요. 서로를 존중하는 대화가 필요해요.',
    loveAdvice: '함께 무언가를 만들어가는 과정에서 관계가 깊어져요. 공동의 목표가 사랑을 키워요.',
    careerAdvice: '팀 프로젝트에서 당신의 기여가 빛을 발해요. 전문성이 인정받고 보상받을 거예요.',
    moneyAdvice: '협력을 통해 수익을 창출할 수 있어요. 함께 일할 때 더 큰 성과가 나와요.' },
  { id: 39, slug: 'four-of-pentacles', name: '펜타클 4', nameEn: 'Four of Pentacles', symbol: '💰', element: '흙', planet: '태양(염소자리)',
    keywordsUp: ['안정추구', '절약', '통제', '소유', '보호'],
    keywordsDown: ['이완', '공유', '변화수용', '집착해소'],
    meaningUp: '가진 것을 지키고 안정을 추구하는 시기예요. 자산을 관리하는 데 집중하고 있어요.',
    meaningDown: '무언가에 너무 집착하고 있어요. 조금은 마음을 놓고 유연해질 필요가 있어요.',
    loveAdvice: '관계에서 소유욕이나 통제욕이 강해질 수 있어요. 조금 더 열린 마음이 필요해요.',
    careerAdvice: '안정적인 직장을 유지하고 싶어 해요. 하지만 너무 변화를 두려워하지 마세요.',
    moneyAdvice: '저축과 절약이 중요한 시기예요. 하지만 너무 인색해지면 인맥이 좁아질 수 있어요.' },
  { id: 40, slug: 'five-of-pentacles', name: '펜타클 5', nameEn: 'Five of Pentacles', symbol: '💰', element: '흙', planet: '수성(황소자리)',
    keywordsUp: ['어려움', '결핍', '외로움', '위기', '도움의필요'],
    keywordsDown: ['회복', '도움수용', '회복시작', '희망'],
    meaningUp: '힘든 시기를 지나고 있어요. 하지만 당신을 도울 손길이 가까이에 있으니 주위를 둘러보세요.',
    meaningDown: '어려움에서 서서히 벗어나고 있어요. 도움을 받아들이는 용기가 필요해요.',
    loveAdvice: '관계에서 소외감이나 외로움을 느낄 수 있어요. 주변에 도움을 요청하세요.',
    careerAdvice: '직장에서 어려움을 겪을 수 있어요. 하지만 도움을 줄 사람이 가까이 있어요.',
    moneyAdvice: '재정적 어려움이 있을 수 있어요. 지원 제도나 도움을 부끄러워하지 마세요.' },
  { id: 41, slug: 'six-of-pentacles', name: '펜타클 6', nameEn: 'Six of Pentacles', symbol: '💰', element: '흙', planet: '달(황소자리)',
    keywordsUp: ['관대함', '나눔', '균형', '수여와수용', '공정'],
    keywordsDown: ['불공정', '부채', '조종', '일방적희생'],
    meaningUp: '주고받는 균형이 아름다운 시기예요. 넉넉한 마음으로 나누면 더 큰 풍요가 돌아와요.',
    meaningDown: '주고받는 관계가 불균형해요. 공정한 관계를 위해 경계를 정하세요.',
    loveAdvice: '관계에서 주고받는 균형이 중요해요. 서로 베푸는 사랑이 아름다운 시기예요.',
    careerAdvice: '멘토링이나 동료 돕기가 보람차요. 베푸는 만큼 인정과 기회가 돌아와요.',
    moneyAdvice: '관대한 마음으로 나누면 더 큰 풍요가 돌아와요. 기부나 나눔이 운을 불러와요.' },
  { id: 42, slug: 'seven-of-pentacles', name: '펜타클 7', nameEn: 'Seven of Pentacles', symbol: '💰', element: '흙', planet: '토성(황소자리)',
    keywordsUp: ['인내', '투자결과', '성찰', '장기계획', '보상'],
    keywordsDown: ['조급함', '포기유혹', '결과지연', '비생산적'],
    meaningUp: '오랫동안 가꾼 노력이 서서히 결실을 맺고 있어요. 조금만 더 기다리면 풍성한 수확이 있을 거예요.',
    meaningDown: '결과가 더디게 와서 답답할 수 있어요. 하지만 지금까지 쌓아온 것은 헛되지 않아요.',
    loveAdvice: '관계에 쏟은 정성이 서서히 결실을 맺고 있어요. 인내가 필요한 시기예요.',
    careerAdvice: '장기 프로젝트의 결과가 조금씩 보이기 시작해요. 조급해하지 말고 끝까지 가세요.',
    moneyAdvice: '장기 투자의 결실이 가까워요. 인내하면 좋은 수익이 기다리고 있어요.' },
  { id: 43, slug: 'eight-of-pentacles', name: '펜타클 8', nameEn: 'Eight of Pentacles', symbol: '💰', element: '흙', planet: '태양(처녀자리)',
    keywordsUp: ['근면', '숙련', '장인정신', '집중', '전문성향상'],
    keywordsDown: ['과로', '완벽주의', '세부몰입과도', '틀깨기'],
    meaningUp: '열심히 몰두하여 실력을 키워가고 있어요. 꾸준한 노력이 전문성으로 이어질 거예요.',
    meaningDown: '너무 디테일에 매몰되어 있어요. 때로는 큰 그림을 보는 것도 필요해요.',
    loveAdvice: '관계를 가꾸는 데 정성을 다하는 시기예요. 꾸준한 노력이 깊은 유대로 이어져요.',
    careerAdvice: '전문성을 높이는 데 집중하세요. 꾸준한 연마가 승진과 성과로 이어질 거예요.',
    moneyAdvice: '기술과 실력을 키우면 수익이 따라와요. 장기적으로 가치가 오르는 곳에 투자하세요.' },
  { id: 44, slug: 'nine-of-pentacles', name: '펜타클 9', nameEn: 'Nine of Pentacles', symbol: '💰', element: '흙', planet: '금성(처녀자리)',
    keywordsUp: ['풍요', '자급자족', '독립', '성취', '여유'],
    keywordsDown: ['과시', '허영', '물질집착', '위장된풍요'],
    meaningUp: '스스로 이룬 성취를 누리는 시기예요. 독립적이고 여유로운 삶을 가꾸고 있어요.',
    meaningDown: '겉모습에 너무 신경 쓰고 있어요. 진정한 풍요는 마음에서 와요.',
    loveAdvice: '스스로 충만한 상태에서 만나는 사랑이 건강해요. 자립적인 매력이 빛나요.',
    careerAdvice: '스스로 이룬 성취를 누리는 시기예요. 독립적인 일에서 큰 성과가 나와요.',
    moneyAdvice: '재정적 독립과 풍요를 누리는 시기예요. 하지만 과시보다는 진짜 자산에 집중하세요.' },
  { id: 45, slug: 'ten-of-pentacles', name: '펜타클 10', nameEn: 'Ten of Pentacles', symbol: '💰', element: '흙', planet: '수성(처녀자리)',
    keywordsUp: ['가족부', '유산', '안정', '장기적성공', '전통'],
    keywordsDown: ['유산분쟁', '가족갈등', '안정위협', '전통충돌'],
    meaningUp: '가족과 함께 누리는 깊은 안정감이 찾아왔어요. 오랜 노력이 대를 이어 이어질 거예요.',
    meaningDown: '가족 내 재정이나 가치관 갈등이 있을 수 있어요. 대화로 풀어가세요.',
    loveAdvice: '가족적이고 안정적인 관계의 정점이에요. 오래 지속되는 사랑과 유대가 있어요.',
    careerAdvice: '장기적으로 안정된 커리어를 구축하는 시기예요. 대를 이어갈 기반을 다지세요.',
    moneyAdvice: '가족의 재정적 안정과 유산이 중요해요. 장기적 자산 관리에 집중하세요.' },
  { id: 46, slug: 'page-of-pentacles', name: '펜타클 시종', nameEn: 'Page of Pentacles', symbol: '💰', element: '흙', planet: '흙(흙의흙)',
    keywordsUp: ['새로운학습', '야망', '기회인식', '근면한시작', '현실적꿈'],
    keywordsDown: ['게으름', '진지함부족', '계획실행지연', '산만함'],
    meaningUp: '새로운 것을 배우고자 하는 의지가 샘솟아요. 현실적인 목표를 향해 첫걸음을 내디디세요.',
    meaningDown: '아이디어만 있고 행동이 없어요. 작게라도 시작하는 것이 중요해요.',
    loveAdvice: '새로운 관계에 대해 진지하게 배워가는 시기예요. 성실한 마음으로 다가가세요.',
    careerAdvice: '새로운 기술이나 자격증을 배우기에 좋은 시기예요. 학습에 투자하세요.',
    moneyAdvice: '재정 관리를 배우기 시작하는 시기예요. 작은 투자라도 꾸준히 시작하세요.' },
  { id: 47, slug: 'knight-of-pentacles', name: '펜타클 기사', nameEn: 'Knight of Pentacles', symbol: '💰', element: '흙', planet: '불(흙의불)',
    keywordsUp: ['성실', '신뢰', '인내', '꾸준함', '루틴'],
    keywordsDown: ['고집', '진부함', '느림', '변화거부'],
    meaningUp: '한결같이 성실하게 목표를 향해 나아가고 있어요. 느리지만 확실한 신뢰의 상징이에요.',
    meaningDown: '너무 경직된 방식에 갇혀 있어요. 유연성을 조금 더 발휘해보세요.',
    loveAdvice: '느리지만 신뢰할 수 있는 관계가 발전해요. 성실함이 사랑을 증명해요.',
    careerAdvice: '꾸준하고 신뢰할 수 있는 업무 태도가 인정받아요. 묵묵히 일하면 보상이 따라와요.',
    moneyAdvice: '꾸준한 저축과 안정적 투자가 재물을 불려요. 느려도 확실한 방식이 최고예요.' },
  { id: 48, slug: 'queen-of-pentacles', name: '펜타클 여왕', nameEn: 'Queen of Pentacles', symbol: '💰', element: '흙', planet: '물(흙의물)',
    keywordsUp: ['돌봄', '실용성', '안정감', '자연친화', '풍요'],
    keywordsDown: ['과잉보호', '물질집착', '자기돌봄소홀', '불안'],
    meaningUp: '현실을 탄탄하게 다지며 주변을 따뜻하게 돌보고 있어요. 풍요로운 안정감의 상징이에요.',
    meaningDown: '남을 돌보느라 자신을 소홀히 하고 있어요. 스스로를 먼저 챙기세요.',
    loveAdvice: '실용적이고 따뜻한 사랑을 주는 시기예요. 관계에 안정감을 심어주세요.',
    careerAdvice: '돌봄과 관리 능력이 빛나는 시기예요. 실용적인 일에서 큰 성과가 나와요.',
    moneyAdvice: '재정 관리와 생활의 안정이 중요해요. 자연스럽고 지속 가능한 풍요를 추구하세요.' },
  { id: 49, slug: 'king-of-pentacles', name: '펜타클 왕', nameEn: 'King of Pentacles', symbol: '💰', element: '흙', planet: '공기(흙의공기)',
    keywordsUp: ['부', '사업성공', '안정', '후원', '권위와풍요'],
    keywordsDown: ['탐욕', '물질만능', '통제과도', '인색함'],
    meaningUp: '물질적 성취와 안정을 누리는 위치에 있어요. 당신의 든든함이 주변에 큰 힘이 돼요.',
    meaningDown: '돈과 권력에 너무 집착하고 있어요. 진정한 풍요는 균형에서 와요.',
    loveAdvice: '안정적이고 넉넉한 사랑을 제공할 수 있어요. 믿음직한 파트너가 되세요.',
    careerAdvice: '사업이나 직장에서 큰 성공과 권위를 누리는 시기예요. 리더십을 발휘하세요.',
    moneyAdvice: '재정적 권위와 성공의 상징이에요. 하지만 탐욕을 경계하고 균형을 잃지 마세요.' },

  // ===== Swords (소드) — 사고 · 갈등 · 지성 / element: 공기 =====
  { id: 50, slug: 'ace-of-swords', name: '소드 에이스', nameEn: 'Ace of Swords', symbol: '⚔️', element: '공기', planet: '쌍둥이자리/천칭자리/물병자리',
    keywordsUp: ['명석함', '돌파', '진실', '새로운아이디어', '결단'],
    keywordsDown: ['혼란', '오해', '잘못된판단', '지연'],
    meaningUp: '선명한 통찰력으로 난관을 돌파할 수 있는 순간이에요. 진실을 향한 칼을 뽑아들었어요.',
    meaningDown: '생각이 정리되지 않아 혼란스러워요. 서두르지 말고 다시 한 번 생각해보세요.',
    loveAdvice: '관계에 대한 명확한 통찰이 필요해요. 솔직한 대화가 관계를 돌파해요.',
    careerAdvice: '날카로운 아이디어와 결단력이 성과를 만들어요. 명확한 목표를 세우고 밀고 나가세요.',
    moneyAdvice: '재정 결정에서 명확한 판단이 필요해요. 정보를 정확히 분석하고 결단하세요.' },
  { id: 51, slug: 'two-of-swords', name: '소드 2', nameEn: 'Two of Swords', symbol: '⚔️', element: '공기', planet: '달(천칭자리)',
    keywordsUp: ['선택의딜레마', '균형', '교착상태', '방어', '블라인드'],
    keywordsDown: ['결단', '정보해금', '막힘해소', '명확한선택'],
    meaningUp: '어려운 선택 앞에서 마음의 눈을 가리고 있어요. 두려움을 내려놓으면 답이 보일 거예요.',
    meaningDown: '외면하던 결정을 내릴 때가 왔어요. 정보를 모두 열어보면 길이 보여요.',
    loveAdvice: '관계에서 중요한 결정을 미루고 있어요. 두려움을 내려놓고 직면하세요.',
    careerAdvice: '커리어의 갈림길에서 망설이고 있어요. 충분한 정보를 모은 후 결단하세요.',
    moneyAdvice: '재정적 선택을 회피하지 마세요. 모든 정보를 확인하고 결정을 내리세요.' },
  { id: 52, slug: 'three-of-swords', name: '소드 3', nameEn: 'Three of Swords', symbol: '⚔️', element: '공기', planet: '토성(천칭자리)',
    keywordsUp: ['심장아픔', '슬픔', '상처', '이별', '실망'],
    keywordsDown: ['회복', '상처치유', '용서', '전진'],
    meaningUp: '마음이 아프고 깊은 상처를 받을 수 있어요. 하지만 이 아픔이 당신을 더 강하게 만들 거예요.',
    meaningDown: '상처가 서서히 아물고 있어요. 스스로를 다독이며 회복해가는 중이에요.',
    loveAdvice: '관계에서 큰 상처를 받을 수 있어요. 하지만 이 아픔을 통해 성장할 거예요.',
    careerAdvice: '직장에서 실망이나 갈등이 있을 수 있어요. 마음을 다스리며 회복하세요.',
    moneyAdvice: '재정적 손실로 마음이 아플 수 있어요. 하지만 회복의 가능성은 항상 있어요.' },
  { id: 53, slug: 'four-of-swords', name: '소드 4', nameEn: 'Four of Swords', symbol: '⚔️', element: '공기', planet: '목성(천칭자리)',
    keywordsUp: ['휴식', '회복', '명상', '준비', '잠시멈춤'],
    keywordsDown: ['무기력', '회피', '지연', '각성필요'],
    meaningUp: '잠시 멈춰 쉬어가야 할 시기예요. 충분한 휴식이 다음 도약을 위한 에너지가 돼요.',
    meaningDown: '너무 오래 쉬고 있어요. 때가 되었으니 다시 일어설 시간이에요.',
    loveAdvice: '관계에서 잠시 거리를 두고 휴식이 필요해요. 마음을 정비하는 시간을 가지세요.',
    careerAdvice: '번아웃을 예방하기 위해 휴식이 필요해요. 재충전 후 더 좋은 결과가 나올 거예요.',
    moneyAdvice: '재정적으로 잠시 숨을 고를 시간이에요. 무리한 결정보다는 휴식과 재정비가 필요해요.' },
  { id: 54, slug: 'five-of-swords', name: '소드 5', nameEn: 'Five of Swords', symbol: '⚔️', element: '공기', planet: '금성(물병자리)',
    keywordsUp: ['갈등', '패배', '승리의대가', '불화', '자기이익'],
    keywordsDown: ['화해', '용서', '갈등종식', '반성'],
    meaningUp: '갈등 속에서 이기는 것만이 전부는 아니라는 것을 깨닫게 돼요. 진정한 승리는 화해에 있어요.',
    meaningDown: '싸움을 멈추고 화해할 준비가 되었어요. 양보하는 것이 더 큰 성과를 가져와요.',
    loveAdvice: '관계에서 다툼이 있을 수 있어요. 이기는 것보다 관계를 지키는 것이 더 중요해요.',
    careerAdvice: '직장에서 경쟁이나 갈등이 있을 수 있어요. 무리하게 이기려 하지 마세요.',
    moneyAdvice: '재정적 분쟁에서 승리하더라도 대가가 클 수 있어요. 타협이 더 나은 선택일 수 있어요.' },
  { id: 55, slug: 'six-of-swords', name: '소드 6', nameEn: 'Six of Swords', symbol: '⚔️', element: '공기', planet: '수성(물병자리)',
    keywordsUp: ['이동', '전환', '잔잔한물살', '회복의이동', '새로운곳'],
    keywordsDown: ['회피', '미해결과거', '저항', '이동지연'],
    meaningUp: '거친 물살을 지나 잔잔한 곳으로 이동하고 있어요. 더 나은 곳을 향한 전환이에요.',
    meaningDown: '과거의 문제를 충분히 해결하지 않고 떠나려 해요. 먼저 마음을 정리하세요.',
    loveAdvice: '관계가 더 나은 단계로 넘어가고 있어요. 과거의 상처를 뒤로하고 전진하세요.',
    careerAdvice: '이직이나 부서 이동으로 더 나은 환경으로 가는 시기예요. 전환을 두려워하지 마세요.',
    moneyAdvice: '재정적으로 더 나은 상태로 전환되고 있어요. 과거의 실수를 교훈 삼아 나아가세요.' },
  { id: 56, slug: 'seven-of-swords', name: '소드 7', nameEn: 'Seven of Swords', symbol: '⚔️', element: '공기', planet: '달(물병자리)',
    keywordsUp: ['전략', '기만', '은밀함', '지혜로운회피', '독립'],
    keywordsDown: ['솔직함', '고백', '계획포기', '정직'],
    meaningUp: '때로는 물러서는 것이 지혜로운 전략이에요. 에너지를 아껴 더 좋은 타이밍을 기다리세요.',
    meaningDown: '숨기고 있는 것이 있다면 솔직해질 때예요. 진실이 더 빠른 해결책이에요.',
    loveAdvice: '관계에서 무언가 숨기고 있다면 솔직해지세요. 비밀은 결국 발각돼요.',
    careerAdvice: '때로는 전략적으로 물러서는 것이 필요해요. 하지만 부정직함은 결국 화를 불러요.',
    moneyAdvice: '재정적으로 은밀한 전략이 필요할 수 있어요. 하지만 투명성을 잃지 마세요.' },
  { id: 57, slug: 'eight-of-swords', name: '소드 8', nameEn: 'Eight of Swords', symbol: '⚔️', element: '공기', planet: '목성(쌍둥이자리)',
    keywordsUp: ['속박', '자기제한', '갇힌느낌', '무력감', '두려움'],
    keywordsDown: ['해방', '자각', '용기', '제한해제'],
    meaningUp: '스스로 만든 생각의 틀에 갇혀 있다고 느껴요. 눈을 가린 끈을 풀면 나갈 수 있는 길이 보여요.',
    meaningDown: '제한이 생각보다 약하다는 것을 깨닫고 있어요. 작은 용기가 큰 해방을 가져와요.',
    loveAdvice: '관계에서 스스로를 가두고 있어요. 두려움을 내려놓으면 자유로워질 수 있어요.',
    careerAdvice: '일에서 한계에 갇혀 있다고 느껴요. 사고의 틀을 깨면 새로운 가능성이 보여요.',
    moneyAdvice: '재정적 두려움이 행동을 가로막고 있어요. 객관적으로 보면 탈출구가 있어요.' },
  { id: 58, slug: 'nine-of-swords', name: '소드 9', nameEn: 'Nine of Swords', symbol: '⚔️', element: '공기', planet: '화성(쌍둥이자리)',
    keywordsUp: ['불안', '악몽', '걱정', '수면부족', '공포'],
    keywordsDown: ['불안해소', '희망', '현실확인', '회복'],
    meaningUp: '밤새 걱정에 시달리고 있어요. 하지만 두려움의 대부분은 현실보다 과장되어 있어요.',
    meaningDown: '불안의 안개가 걷히고 있어요. 현실을 확인하면 생각보다 괜찮다는 걸 알게 될 거예요.',
    loveAdvice: '관계에 대한 걱정이 밤을 잠 못 이루게 해요. 하지만 실제보다 과장되어 있을 거예요.',
    careerAdvice: '일에 대한 불안이 크지만, 실제로는 생각보다 잘 해나가고 있어요.',
    moneyAdvice: '재정적 걱정이 과도할 수 있어요. 객관적으로 재정을 점검해보면 안심될 거예요.' },
  { id: 59, slug: 'ten-of-swords', name: '소드 10', nameEn: 'Ten of Swords', symbol: '⚔️', element: '공기', planet: '태양(쌍둥이자리)',
    keywordsUp: ['끝', '바닥', '고통의종결', '전환점', '해방'],
    keywordsDown: ['회복', '재기', '최악지남', '재출발'],
    meaningUp: '가장 힘든 순간을 지나고 있어요. 하지만 이것이 끝이면 새로운 시작이에요. 더 이상 내려갈 곳은 없어요.',
    meaningDown: '최악의 시기를 넘겼어요. 이제는 오르막길뿐이에요. 희망을 가지세요.',
    loveAdvice: '관계의 가장 힘든 끝을 맞이할 수 있어요. 하지만 이 끝은 새로운 시작의 문이에요.',
    careerAdvice: '커리어의 바닥을 경험할 수 있어요. 하지만 여기서부터는 회복뿐이에요.',
    moneyAdvice: '재정적으로 최악의 시기일 수 있어요. 하지만 더 이상 나빠질 것이 없으니 회복만 남았어요.' },
  { id: 60, slug: 'page-of-swords', name: '소드 시종', nameEn: 'Page of Swords', symbol: '⚔️', element: '공기', planet: '흙(공기의흙)',
    keywordsUp: ['호기심', '새로운아이디어', '경계심', '지적탐구', '기민함'],
    keywordsDown: ['가벼움', '실행력부족', '말과행동괴리', '분산'],
    meaningUp: '새로운 지식에 대한 호기심이 샘솟아요. 날카로운 관찰력으로 상황을 파악하고 있어요.',
    meaningDown: '아이디어는 많지만 실행이 부족해요. 하나를 정해 끝까지 밀고 나가보세요.',
    loveAdvice: '관계에 대해 호기심이 많고 관찰력이 예리해요. 지적인 대화가 매력적으로 다가와요.',
    careerAdvice: '새로운 분야를 탐구하기 좋은 시기예요. 정보 수집과 학습에 집중하세요.',
    moneyAdvice: '재정 정보에 호기심이 많아요. 다양한 투자 정보를 수집하되 실행력을 키우세요.' },
  { id: 61, slug: 'knight-of-swords', name: '소드 기사', nameEn: 'Knight of Swords', symbol: '⚔️', element: '공기', planet: '불(공기의불)',
    keywordsUp: ['추진력', '야망', '직선적행동', '용기', '속도'],
    keywordsDown: ['무모함', '충동', '경솔', '과도한경쟁'],
    meaningUp: '목표를 향해 맹렬하게 돌진하는 에너지가 가득해요. 결단력 있게 행동하면 빠른 성과가 있어요.',
    meaningDown: '너무 빨리 달리고 있어요. 속도를 조절하지 않으면 넘어질 수 있어요.',
    loveAdvice: '적극적이고 직진하는 사랑을 보여줘요. 하지만 상대의 속도도 배려하세요.',
    careerAdvice: '추진력이 강한 시기예요. 빠른 결단과 실행이 성과를 만들어요.',
    moneyAdvice: '빠른 재정 결정이 유리할 수 있어요. 하지만 충동적 투자는 위험해요.' },
  { id: 62, slug: 'queen-of-swords', name: '소드 여왕', nameEn: 'Queen of Swords', symbol: '⚔️', element: '공기', planet: '물(공기의물)',
    keywordsUp: ['독립', '통찰', '객관성', '직설적', '지혜'],
    keywordsDown: ['냉정함', '비판적', '고립', '감정차단'],
    meaningUp: '명석한 이성과 날카로운 통찰로 상황을 판단하고 있어요. 독립적인 사고가 힘이 돼요.',
    meaningDown: '너무 차갑고 비판적일 수 있어요. 따뜻함도 함께 품으면 더 완벽해져요.',
    loveAdvice: '독립적이고 지적인 관계를 원해요. 솔직하고 명확한 대화가 중요해요.',
    careerAdvice: '객관적이고 공정한 판단력이 빛나요. 독립적인 일에서 큰 성과가 나와요.',
    moneyAdvice: '재정 결정에서 객관성이 중요해요. 감정을 배제하고 이성적으로 판단하세요.' },
  { id: 63, slug: 'king-of-swords', name: '소드 왕', nameEn: 'King of Swords', symbol: '⚔️', element: '공기', planet: '공기(공기의공기)',
    keywordsUp: ['권위', '진실', '지성', '공정한판단', '리더십'],
    keywordsDown: ['독단', '냉혹함', '조종', '권위주의'],
    meaningUp: '명석한 두뇌와 공정한 판단력으로 상황을 주도하고 있어요. 지적 권위가 인정받는 시기예요.',
    meaningDown: '자신의 생각만 옳다고 고집하고 있어요. 타인의 의견에도 귀 기울이세요.',
    loveAdvice: '이성적이고 공정한 관계를 이끄는 시기예요. 명확한 의사소통이 핵심이에요.',
    careerAdvice: '지적 권위와 리더십이 인정받는 시기예요. 전문성으로 팀을 이끄세요.',
    moneyAdvice: '재정 결정에서 전문성과 공정함이 필요해요. 전문가의 조언을 활용하세요.' },

  // ===== Wands (완드) — 행동 · 열정 · 창조 / element: 불 =====
  { id: 64, slug: 'ace-of-wands', name: '완드 에이스', nameEn: 'Ace of Wands', symbol: '🔥', element: '불', planet: '양자리/사자자리/사수자리',
    keywordsUp: ['영감', '새로운도전', '창조적불꽃', '열정', '시작'],
    keywordsDown: ['열정식음', '지연', '기회주저', '동력상실'],
    meaningUp: '가슴 속에서 불꽃이 타오르는 새로운 영감이 찾아왔어요. 이 열정을 행동으로 옮길 때예요.',
    meaningDown: '열정이 꺼지려 하고 있어요. 다시 불을 지필 수 있는 새로운 자극이 필요해요.',
    loveAdvice: '새로운 사랑에 대한 열정이 타오르는 시기예요. 마음의 불꽃을 따라가보세요.',
    careerAdvice: '새로운 프로젝트나 창업의 영감이 떠올라요. 이 열정을 행동으로 옮기세요.',
    moneyAdvice: '새로운 수익 아이디어에 열정이 솟아요. 하지만 실행으로 옮기는 것이 중요해요.' },
  { id: 65, slug: 'two-of-wands', name: '완드 2', nameEn: 'Two of Wands', symbol: '🔥', element: '불', planet: '화성(양자리)',
    keywordsUp: ['계획', '미래선택', '시야확장', '결심', '지도'],
    keywordsDown: ['우유부단', '두려움', '계획실행괴리', '안주함'],
    meaningUp: '더 넓은 세상을 바라보며 미래를 계획하고 있어요. 용기 있게 첫걸음을 내디디세요.',
    meaningDown: '계획만 세우고 행동으로 옮기지 못하고 있어요. 작게라도 시작하세요.',
    loveAdvice: '관계의 미래를 내다보며 계획하는 시기예요. 함께할 비전을 공유하세요.',
    careerAdvice: '장기 커리어 계획을 세우는 시기예요. 더 넓은 시야로 기회를 살펴보세요.',
    moneyAdvice: '재정적 미래를 계획하는 시기예요. 장기적 투자 전략을 세우세요.' },
  { id: 66, slug: 'three-of-wands', name: '완드 3', nameEn: 'Three of Wands', symbol: '🔥', element: '불', planet: '태양(양자리)',
    keywordsUp: ['확장', '전망', '진전', '대기', '해외기회'],
    keywordsDown: ['지연', '기대저하', '방해', '단기근시'],
    meaningUp: '앞에 펼쳐진 가능성의 지평이 넓어지고 있어요. 뿌린 씨앗이 싹트기를 기다리는 시기예요.',
    meaningDown: '결과가 예상보다 늦어질 수 있어요. 조급해하지 말고 더 넓은 시야를 가지세요.',
    loveAdvice: '관계가 더 넓은 세상으로 확장되는 시기예요. 함께 성장하는 비전을 품으세요.',
    careerAdvice: '사업이나 커리어가 확장되는 시기예요. 해외나 새로운 시장의 기회를 노려보세요.',
    moneyAdvice: '투자가 확장되고 수익이 성장하는 시기예요. 더 넓은 시장을 바라보세요.' },
  { id: 67, slug: 'four-of-wands', name: '완드 4', nameEn: 'Four of Wands', symbol: '🔥', element: '불', planet: '금성(양자리)',
    keywordsUp: ['축하', '안정', '가족모임', '성취인정', '터전'],
    keywordsDown: ['불안정', '축하지연', '소속감결핍', '갈등'],
    meaningUp: '이루어 낸 성과를 축하하며 안정감을 느끼는 시기예요. 사랑하는 사람들과 기쁨을 나누세요.',
    meaningDown: '안정감이 흔들릴 수 있어요. 소속감을 다시 확인하는 노력이 필요해요.',
    loveAdvice: '관계의 이정표를 축하하는 기쁜 시기예요. 함께 이룬 것을 축하하세요.',
    careerAdvice: '프로젝트 완성이나 승진 등 성취를 축하받는 시기예요. 동료와 기쁨을 나누세요.',
    moneyAdvice: '재정적 목표 달성을 축하할 수 있어요. 하지만 안정감을 유지하려면 계속 관리하세요.' },
  { id: 68, slug: 'five-of-wands', name: '완드 5', nameEn: 'Five of Wands', symbol: '🔥', element: '불', planet: '토성(사자자리)',
    keywordsUp: ['경쟁', '갈등', '의견충돌', '긴장', '훈련'],
    keywordsDown: ['갈등해소', '협력', '타협', '평화'],
    meaningUp: '치열한 경쟁이나 의견 충돌이 있는 시기예요. 하지만 이 과정이 당신을 더 강하게 단련시켜요.',
    meaningDown: '갈등이 잦아들고 있어요. 서로의 의견을 존중하며 타협점을 찾으세요.',
    loveAdvice: '관계에서 의견 충돌이 있을 수 있어요. 건설적인 경쟁은 관계를 단단하게 만들어요.',
    careerAdvice: '직장에서 경쟁이 치열해요. 하지만 이 긴장이 당신의 실력을 끌어올려요.',
    moneyAdvice: '재정적 경쟁이나 분쟁이 있을 수 있어요. 건설적인 방향으로 에너지를 쓰세요.' },
  { id: 69, slug: 'six-of-wands', name: '완드 6', nameEn: 'Six of Wands', symbol: '🔥', element: '불', planet: '목성(사자자리)',
    keywordsUp: ['승리', '인정', '명예', '성공', '자신감'],
    keywordsDown: ['인하하락', '자만', '인정결핍', '지나친기대'],
    meaningUp: '노력이 결실을 맺어 승리와 인정을 받는 시기예요. 당당하게 성과를 누리세요.',
    meaningDown: '자만심이 생길 수 있어요. 겸손함을 잃지 않아야 더 오래 성공할 수 있어요.',
    loveAdvice: '관계에서 인정받고 자신감이 넘치는 시기예요. 당신의 매력이 빛나요.',
    careerAdvice: '승리와 인정의 시기예요! 노력이 결실을 맺어 동료들의 존경을 받아요.',
    moneyAdvice: '재정적 성공을 이루는 시기예요. 하지만 자만하지 말고 겸손함을 유지하세요.' },
  { id: 70, slug: 'seven-of-wands', name: '완드 7', nameEn: 'Seven of Wands', symbol: '🔥', element: '불', planet: '화성(사자자리)',
    keywordsUp: ['방어', '의지', '독립수호', '용기', '끝까지버틈'],
    keywordsDown: ['양보', '압도당함', '포기', '지침'],
    meaningUp: '자신의 자리를 끝까지 사수해야 하는 시기예요. 당신의 신념에 용기를 가지세요.',
    meaningDown: '혼자서 감당하기 벅찰 수 있어요. 도움을 요청하는 것도 지혜예요.',
    loveAdvice: '관계에서 자신을 지켜야 하는 시기예요. 건강한 경계가 필요해요.',
    careerAdvice: '직장에서 자신의 입지를 방어해야 해요. 신념을 굽히지 마세요.',
    moneyAdvice: '재정적 입지를 지켜야 하는 시기예요. 무리한 압력에 굴하지 마세요.' },
  { id: 71, slug: 'eight-of-wands', name: '완드 8', nameEn: 'Eight of Wands', symbol: '🔥', element: '불', planet: '수성(사수자리)',
    keywordsUp: ['속도', '신속한행동', '소통', '진전', '메시지'],
    keywordsDown: ['지연', '오해', '마비', '정체'],
    meaningUp: '빠르게 진행되는 변화와 소통의 흐름 속에 있어요. 흐름을 타면 빠른 성과를 얻을 수 있어요.',
    meaningDown: '흐름이 멈추거나 지연될 수 있어요. 조급해하지 말고 다음 바람을 기다리세요.',
    loveAdvice: '관계가 빠르게 발전하는 시기예요. 소통이 활발하고 진전이 빨라요.',
    careerAdvice: '일이 빠르게 진행되는 시기예요. 흐름을 타면 큰 성과를 빠르게 얻어요.',
    moneyAdvice: '재정적 변화가 빠르게 진행돼요. 기회를 빨리 잡는 것이 중요해요.' },
  { id: 72, slug: 'nine-of-wands', name: '완드 9', nameEn: 'Nine of Wands', symbol: '🔥', element: '불', planet: '달(사수자리)',
    keywordsUp: ['끈기', '인내', '마지막방어', '경계', '회복력'],
    keywordsDown: ['포기', '번아웃', '지침', '회피'],
    meaningUp: '오랜 투쟁 끝에 마지막 고비에 서 있어요. 조금만 더 버티면 당신의 것이 될 거예요.',
    meaningDown: '체력이 한계에 다다랐어요. 잠시 쉬어가며 에너지를 보충할 필요가 있어요.',
    loveAdvice: '관계에서 오래된 시련을 견디고 있어요. 조금만 더 인내하면 안정이 와요.',
    careerAdvice: '오랜 프로젝트의 마지막 고비예요. 끈기를 발휘하면 곧 결실이 와요.',
    moneyAdvice: '재정적 어려움을 오래 견뎌왔어요. 조금만 더 버티면 회복이 시작돼요.' },
  { id: 73, slug: 'ten-of-wands', name: '완드 10', nameEn: 'Ten of Wands', symbol: '🔥', element: '불', planet: '토성(사수자리)',
    keywordsUp: ['부담', '책임과다', '무거운짐', '고군분투', '임박한해방'],
    keywordsDown: ['짐내려놓기', '위임', '휴식', '부담해소'],
    meaningUp: '너무 많은 책임을 짊어지고 있어요. 무거운 짐이지만 곧 내려놓을 수 있는 끝점이 가까워요.',
    meaningDown: '모든 것을 혼자 하려 하지 마세요. 짐을 나누면 훨씬 가벼워질 거예요.',
    loveAdvice: '관계에서 너무 많은 짐을 지고 있어요. 부담을 나누는 것이 필요해요.',
    careerAdvice: '과로에 시달리고 있어요. 업무를 위임하고 짐을 나누세요.',
    moneyAdvice: '재정적 부담이 너무 크게 느껴져요. 우선순위를 정하고 부담을 줄이세요.' },
  { id: 74, slug: 'page-of-wands', name: '완드 시종', nameEn: 'Page of Wands', symbol: '🔥', element: '불', planet: '흙(불의흙)',
    keywordsUp: ['탐험', '열정', '자유영혼', '새로운모험', '영감'],
    keywordsDown: ['산만함', '실행지연', '변덕', '인내부족'],
    meaningUp: '새로운 세계를 향한 호기심과 열정이 넘쳐요. 두려움 없이 모험을 시작해보세요.',
    meaningDown: '이것저것 시작하고 마무리를 못 해요. 하나에 집중하는 훈련이 필요해요.',
    loveAdvice: '새로운 만남에 대한 설렘이 가득해요. 자유로운 마음으로 다가가보세요.',
    careerAdvice: '새로운 분야를 탐험하고 싶은 열정이 샘솟아요. 호기심을 따라가보세요.',
    moneyAdvice: '새로운 수익 기회에 호기심이 많아요. 하지만 인내심을 가지고 끝까지 밀고 나가세요.' },
  { id: 75, slug: 'knight-of-wands', name: '완드 기사', nameEn: 'Knight of Wands', symbol: '🔥', element: '불', planet: '불(불의불)',
    keywordsUp: ['에너지', '열정', '추진력', '모험심', '카리스마'],
    keywordsDown: ['충동', '경솔', '실행착오', '과도한경쟁'],
    meaningUp: '불타는 열정으로 앞으로 나아가는 에너지가 가득해요. 자신감을 가지고 도전하세요.',
    meaningDown: '충동적으로 움직이고 있어요. 한 박자 쉬어가는 것이 더 나은 결과를 가져와요.',
    loveAdvice: '열정적이고 에너지 넘치는 사랑을 보여줘요. 하지만 상대의 페이스도 존중하세요.',
    careerAdvice: '강한 추진력으로 빠른 성과를 만들어요. 하지만 무리하지 마세요.',
    moneyAdvice: '에너지 넘치는 투자가 유혹적이에요. 하지만 충동적 결정은 피하세요.' },
  { id: 76, slug: 'queen-of-wands', name: '완드 여왕', nameEn: 'Queen of Wands', symbol: '🔥', element: '불', planet: '물(불의물)',
    keywordsUp: ['자신감', '카리스마', '독립성', '따뜻한리더십', '결단력'],
    keywordsDown: ['질투', '독선', '과도한지배욕', '불안'],
    meaningUp: '당당하고 매력적인 에너지로 주변을 이끄는 시기예요. 자신감이 가장 큰 무기예요.',
    meaningDown: '자존심이 너무 센 나머지 관계가 틀어질 수 있어요. 조금은 부드러워질 필요가 있어요.',
    loveAdvice: '당당하고 매력적인 시기예요. 자신감 있는 태도가 사랑을 끌어당겨요.',
    careerAdvice: '카리스마 있는 리더십으로 팀을 이끄는 시기예요. 자신감이 성과를 만들어요.',
    moneyAdvice: '자신감 있는 재정 결정이 유리해요. 하지만 과신은 금물이에요.' },
  { id: 77, slug: 'king-of-wands', name: '완드 왕', nameEn: 'King of Wands', symbol: '🔥', element: '불', planet: '공기(불의공기)',
    keywordsUp: ['리더십', '비전', '대담함', '카리스마', '창조적권위'],
    keywordsDown: ['무모함', '독단', '성급함', '과도한통제'],
    meaningUp: '비전을 품고 사람들을 이끄는 자연스러운 리더의 자리에 있어요. 대담하게 앞장서세요.',
    meaningDown: '독단적으로 이끌고 있어요. 팀의 목소리에 귀 기울이면 더 위대한 성과가 나와요.',
    loveAdvice: '관계를 이끄는 주도적인 위치예요. 따뜻한 리더십으로 사랑을 이끄세요.',
    careerAdvice: '리더십과 비전으로 큰 성과를 이루는 시기예요. 팀을 영감으로 이끄세요.',
    moneyAdvice: '대담한 재정 결정이 유리한 시기예요. 비전을 갖고 투자하세요.' },
];

/** All 78 cards (Major + Minor Arcana) */
export const ALL_CARDS = [...MAJOR_ARCANA, ...MINOR_ARCANA];

/** Get card by slug */
export function getCardBySlug(slug) {
  return ALL_CARDS.find((c) => c.slug === slug);
}

/** Get next card (wraps around) */
export function getNextCard(id) {
  const nextId = (id + 1) % ALL_CARDS.length;
  return ALL_CARDS.find((c) => c.id === nextId);
}

/** Get previous card (wraps around) */
export function getPrevCard(id) {
  const prevId = (id - 1 + ALL_CARDS.length) % ALL_CARDS.length;
  return ALL_CARDS.find((c) => c.id === prevId);
}
